<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Engine/Common/Mirage.Common.csproj" />
    <ProjectReference Include="..\Engine\Noding\Mirage.Noding.csproj" />
    <ProjectReference Include="..\Engine\Scheduling\Mirage.Scheduling.csproj" />
    <ProjectReference Include="..\Engine\Handling\Mirage.Handling.csproj" />
    <ProjectReference Include="../Engine/Windowing/Mirage.Windowing.csproj" />
    <ProjectReference Include="..\Engine\Math\Mirage.Math.csproj" />
    <ProjectReference Include="..\Engine\Spatial\Mirage.Spatial.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Handling\" />
  </ItemGroup>
</Project>
