<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Mirage.Common.csproj" />
    <ProjectReference Include="..\Math\Mirage.Math.csproj" />
    <ProjectReference Include="..\Scheduling\Mirage.Scheduling.csproj" />
  </ItemGroup>

  <ItemGroup>

    <PackageReference Include="SDL3-CS" Version="3.4.16.1" />
    <PackageReference Include="SDL3-CS.Linux" Version="3.4.16" />
    <PackageReference Include="SDL3-CS.Windows" Version="3.4.16" />
    <PackageReference Include="SDL3-CS.MacOS" Version="3.4.16" />
  </ItemGroup>
</Project>
