<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Engine/Common/Mirage.Common.csproj" />
    <ProjectReference Include="../../Engine/Handling/Mirage.Handling.csproj" />
    <ProjectReference Include="../../Engine/Noding/Mirage.Noding.csproj" />
    <ProjectReference Include="../../Engine/Rendering/Mirage.Rendering.csproj" />
    <ProjectReference Include="../../Engine/Scheduling/Mirage.Scheduling.csproj" />
    <ProjectReference Include="../../Engine/Simulating/Mirage.Simulating.csproj" />
    <ProjectReference Include="../../Engine/Windowing/Mirage.Windowing.csproj" />
  </ItemGroup>
</Project>
