<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common\Mirage.Common.csproj" />
    <ProjectReference Include="..\Importing\Mirage.Importing.csproj" />
    <ProjectReference Include="..\Noding\Mirage.Noding.csproj" />
    <ProjectReference Include="..\Numerics\Mirage.Numerics.csproj" />
    <ProjectReference Include="..\Scheduling\Mirage.Scheduling.csproj" />
    <ProjectReference Include="..\Spatial\Mirage.Spatial.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="StbImageSharp" Version="2.30.16" />
    <PackageReference Include="Vortice.Dxc" Version="3.8.3" />
  </ItemGroup>
</Project>
